server:
  port: 80
spring:
  application:
    name: statistics
  datasource:
    url: jdbc:mysql://rm-bp162lib12d6f3vyn.mysql.rds.aliyuncs.com:3306/answer?characterEncoding=UTF-8&useSSL=false&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: answer
    password: answer@1101
    driver-class-name: com.mysql.cj.jdbc.Driver
    initial-size: 10
    min-idle: 10
    max-active: 30
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-test-query: SELECT 1
  redis:
    host: r-bp1incmx0ova9dploj.redis.rds.aliyuncs.com
    port: 6379
    password: Yssj@1101
    jedis:
      pool:
        max-wait: 3000
        max-idle: 20
        max-active: 100
    cluster:
      timeout: 3000

uums:
  host: http://uums-svc:8080/uums
  userTokenValid: /v1/api/user/verifyLogin